#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_5_3_1_gnueabihf/libexec/gcc/arm-linux-gnueabihf/4.9.3:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_5_3_1_gnueabihf/bin/arm-linux-gnueabihf-gcc \
    "$@"
