#!/bin/bash --norc

PATH="external/rpi_gcc_5_4_1_gnueabihf/libexec/gcc/arm-rpi-linux-gnueabihf/5.4.1:$PATH" \
    exec \
    external/rpi_gcc_5_4_1_gnueabihf/bin/arm-rpi-linux-gnueabihf-gcc \
    "$@"
