#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_5_3_1_gnueabi/libexec/gcc/arm-linux-gnueabi/4.9.3:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_5_3_1_gnueabi/bin/arm-linux-gnueabi-gcc \
    "$@"
